version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    user: root
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb_data:/data
    expose:
      - 8000
    networks:
      dynamodb-local-network: {}
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network
networks:
  dynamodb-local-network:
    name: dynamodb-local-network
