AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template FastAPI


Parameters:
  Environment:
    Description: Environment in which the resources will be deploy
    Type: String
    Default: Environment
  SQSBatchSize:
    Description: sqs batch size
    Type: String
    Default: SQSBatchSize
  AuthorizerTimeout:
    Description: authorizer timeout
    Type: String
    Default: AuthorizerTimeout
  TokenExpiration:
    Description: token expiration
    Type: String
    Default: TokenExpiration
  GlobalTimeout:
    Description: global timeout
    Type: String
    Default: GlobalTimeout
  DynamoDBReadCapacityUnits:
    Description: dynamodb read capacity units
    Type: String
    Default: DynamoDBReadCapacityUnits
  DynamoDBWriteCapacityUnits:
    Description: dynamodb write capacity units
    Type: String
    Default: DynamoDBWriteCapacityUnits
  SecretKey:
    Description: Secret Key
    Type: String
    Default: SecretKey
  StackName:
    Description: Stack Name inmensity
    Type: String
    Default: StackName
  SendGridApiKey:
    Description: Send Grid Api Key
    Type: String
    Default: SendGridApiKey
Resources:

  # Dynamo Stack
  DynamoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/template_dynamo.yaml
      Parameters:
        StackName: !Ref StackName
        Environment: !Ref Environment
        DynamoDBReadCapacityUnits: !Ref DynamoDBReadCapacityUnits
        DynamoDBWriteCapacityUnits: !Ref DynamoDBWriteCapacityUnits
      Tags:
        Environment: !Ref Environment
        StackName: !Ref StackName
      TimeoutInMinutes: 10

  # Authorizer Stack
  AuthorizerStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/template_authorizer.yaml
      Parameters:
        GlobalTimeout: !Ref GlobalTimeout
        Environment: !Ref Environment
        SecretKey: !Ref SecretKey
        StackName: !Ref StackName
        # Dynamo
        DynamoTableName: !GetAtt DynamoStack.Outputs.DynamoTableName
      Tags:
        Environment: !Ref Environment
        StackName: !Ref StackName
      TimeoutInMinutes: 10

  ApiGatewayStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/template_api.yaml
      Parameters:
        Environment: !Ref Environment
        SecretKey: !Ref SecretKey
        Environment: !Ref Environment
        GlobalTimeout: !Ref GlobalTimeout
        TokenExpiration: !Ref TokenExpiration
        AuthorizerTimeout: !Ref AuthorizerTimeout
        SQSBatchSize: !Ref SQSBatchSize
        SendGridApiKey: !Ref SendGridApiKey
        StackName: !Ref StackName
        # Dynamo
        DynamoTableName: !GetAtt DynamoStack.Outputs.DynamoTableName
        DynamoDBTable: !GetAtt DynamoStack.Outputs.DynamoDBTable
        DynamoDBTableLogs: !GetAtt DynamoStack.Outputs.DynamoDBTableLogs
        AuthorizerArn: !GetAtt AuthorizerStack.Outputs.AuthorizerArn
      Tags:
        Environment: !Ref Environment
        StackName: !Ref StackName
      TimeoutInMinutes: 10
