AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack Microservices

Parameters:
  Environment:
    Description: Environment in which the resources will be deploy
    Type: String
    Default: local
  DynamoTableName:
    Description: Dynamo Table name
    Type: String
  SecretKey:
    Description: Secret Key
    Type: String
  GlobalTimeout:
    Description: Global timeout
    Type: String
  StackName:
    Description: stack Name
    Type: String
    Default: stack-stack-name
  DynamoDBTableLogs:
    Description: DynamoDB Table
    Type: String
  DynamoDBTable:
    Description: DynamoDB Table
    Type: String
Globals:
  Function:
    Timeout: !Ref GlobalTimeout
    Tracing: Active
    MemorySize: 256
    Handler: app.handler
    Runtime: python3.12
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        SECRET_KEY: !Ref SecretKey
        ENVIRONMENT_SAM: !Ref Environment
        REGION_AWS: !Ref AWS::Region
Resources:
  LayerShared:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer for Data Ingestor
      ContentUri: ../shared
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: makefile

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/authorizer
      FunctionName: !Sub authorizer-${StackName}-${Environment}
      Description: !Sub Authorizer microservice «${Environment}»

      VpcConfig: ~
      Environment:
        Variables:
          FUNCTION_NAME: !Sub auth-${StackName}-${Environment}
          DYNAMO_DB_TABLE_LOGS: !Ref DynamoDBTableLogs
          DYNAMO_DB_TABLE_AUTH: !Ref DynamoTableName
          DYNAMO_DB_TABLE: !Ref DynamoDBTable
      Layers:
        - !Ref LayerShared
      Policies:
        - AmazonDynamoDBFullAccess

Outputs:
  AuthorizerArn:
    Value: !GetAtt AuthorizerFunction.Arn
    Export:
      Name: !Sub "${StackName}-AuthoArn"
  AuthorizerFunction:
    Value: !Ref AuthorizerFunction
    Export:
      Name: !Sub "${StackName}-AuthoFun"