AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack Microservices

Parameters:
  StackName:
    Description: stack Name
    Type: String
    Default: stack-stack-name
  Environment:
    Description: Environment in which the resources will be deploy
    Type: String
    Default: local
  DynamoDBReadCapacityUnits:
    Description: dynamodb read capacity units
    Type: String
    Default: 5
  DynamoDBWriteCapacityUnits:
    Description: dynamodb write capacity units
    Type: String
    Default: 5

Resources:

  AuthorizersDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbAuthoTable${Environment}
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DynamoDBWriteCapacityUnits


  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbTable${Environment}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoDBReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoDBWriteCapacityUnits
        - IndexName: GSI_Email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref DynamoDBReadCapacityUnits
            WriteCapacityUnits: !Ref DynamoDBWriteCapacityUnits
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DynamoDBWriteCapacityUnits

  DynamoDBTableLogs:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub DbTableLogs${Environment}
      AttributeDefinitions:
        - AttributeName: api
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: api
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref DynamoDBReadCapacityUnits
        WriteCapacityUnits: !Ref DynamoDBWriteCapacityUnits

Outputs:
  DynamoTableName:
    Value: !Sub DbAuthoTable${Environment}
    Export:
      Name: !Sub DbAuthoTable${Environment}
  DynamoDBTable:
    Value: !Sub DbTable${Environment}
    Export:
      Name: !Sub DbTable${Environment}
  DynamoDBTableLogs:
    Value: !Sub DbTableLogs${Environment}
    Export:
      Name: !Sub DbTableLogs${Environment}
